GARNAME = Test-Simple
GARVERSION = 0.98
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/MS/MSCHWERN/

LIBDEPS = apps/perl/perl

DESCRIPTION = Basic utilities for writing tests.  
AUTHOR = Michael G Schwern
URL = http://search.cpan.org/~mschwern/
LICENSE = Perl

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

