GARNAME = Filesys-DiskUsage
GARVERSION = 0.04
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = $(CPAN_MIRROR)/authors/id/C/CO/COG/ http://www.cpan.org/authors/id/C/CO/COG/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/C/CO/COG/

LIBDEPS = apps/perl/perl

DESCRIPTION = Estimate file space usage
AUTHOR = Jose Castro
URL = http://cpan.uwinnipeg.ca/~cog
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

