diff --speed-large-files --minimal -Nru tmp/MonaLisa.v13.11.04/Makefile work/MonaLisa.v13.11.04/Makefile
--- tmp/MonaLisa.v13.11.04/Makefile	1970-01-01 01:00:00.000000000 +0100
+++ work/MonaLisa.v13.11.04/Makefile	2013-01-30 11:38:36.020868636 +0100
@@ -0,0 +1,29 @@
+build:
+	tar zxvf $(DISTNAME).tar.gz
+	sed -i -e 's/`id /`env LD_LIBRARY_PATH= id /' MonaLisa.v13.11.04/Service/CMD/ML_SER
+ifneq ($(shell uname -s),Darwin)
+	LD_LIBRARY_PATH= wget http://monalisa.cern.ch/download/java/jre-$(JAVA_VERSION)-$(JAVA_PLATFORM).tar.gz && \
+	(cd $(DISTNAME) &&  \
+	tar -xzf ../jre-$(JAVA_VERSION)-$(JAVA_PLATFORM).tar.gz ;\
+	JAVA_HOME=jre* && ln -sf $$JAVA_HOME java && cd $$JAVA_HOME ; \
+	rm -rf demo man sample src.zip jre/plugin jre/javaws)
+else
+	echo Java is already installed on Darwin
+endif
+	(cd $(DISTNAME)/Service/lib && \
+	for site in $(MASTER_SITES) ; do \
+	    env LD_LIBRARY_PATH= DYLD_LIBRARY_PATH=  PATH=/sw/bin:/sw/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin curl --fail $${site}../fdt/fdt.jar -o fdt.jar && break ; \
+	done ; test -s fdt.jar)
+
+install:
+	rm -rf $(PREFIX)/$(DISTNAME) ; rm -f $(PREFIX)/MonaLisa ; \
+	mkdir -p $(PREFIX); \
+	find $(DISTNAME) -exec touch {} \; ; \
+	cp -r $(DISTNAME) $(PREFIX)/ ; \
+	echo "Copying AliEn specific files..." ; \
+	mkdir -p $(PREFIX)/$(DISTNAME); \
+	cp install.sh install2.sh $(PREFIX)/$(DISTNAME)/; \
+	(cd ../../files ; \
+	find bin AliEn Control Service ! -path \*/CVS* -type d -exec mkdir -p $(PREFIX)/$(DISTNAME)/{} \; ; \
+	find bin AliEn Control Service ! -path \*/CVS* -type f -exec cp {} $(PREFIX)/$(DISTNAME)/{} \; ) ; \
+	cd $(PREFIX)/ ; ln -sf $(DISTNAME) MonaLisa ; chmod -R a+r MonaLisa ; \
