GARNAME = SQL-Statement
GARVERSION = 1.33
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/

LIBDEPS = apps/perl/DBI apps/perl/Params-Util apps/perl/Clone

DESCRIPTION = Small SQL parser and engine
AUTHOR = Jeff Zucker
URL = http://cpan.uwinnipeg.ca/~jzucker
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

