GARNAME = Cache-Cache
GARVERSION = 1.06
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/J/JS/JSWARTZ/

LIBDEPS = apps/perl/Error apps/perl/Digest-SHA1

DESCRIPTION = Generic cache interface and implementations
LICENSE = Perl
URL = http://cpan.uwinnipeg.ca/~dclinton
AUTHOR = DeWitt Clinton

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

