GARNAME = Convert-UU
GARVERSION = 0.5201
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AN/ANDK/

LIBDEPS = apps/perl/perl

DESCRIPTION = UUencode and UUdecode
AUTHOR = Andreas J. Koenig
URL = http://cpan.uwinnipeg.ca/~andk
LICENSE = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

