GARNAME = Tie-CPHash
GARVERSION = 1.04
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/C/CJ/CJM/Tie-CPHash-1.04.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/C/CJ/CJM/

LIBDEPS = apps/perl/perl

DESCRIPTION = Case preserving but case insensitive hash table
AUTHOR = Christopher J. Madsen
URL    = http://search.cpan.org/~cjm/
LICENSE= Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

