GARNAME = Class-MethodMaker
GARVERSION = 2.16
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://backpan.perl.org/authors/id/S/SC/SCHWIGON/class-methodmaker/ http://search.cpan.org/CPAN/authors/id/S/SC/SCHWIGON/class-methodmaker/

LIBDEPS = apps/perl/perl

DESCRIPTION = Create generic class methods
AUTHOR = Martyn J. Pearce
URL = http://cpan.uwinnipeg.ca/~fluffy
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

