GARNAME = Log-Dispatch
GARVERSION = 2.26
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://cpan.mirror.solnet.ch/authors/id/D/DR/DROLSKY/

LIBDEPS = apps/perl/Params-Validate

DESCRIPTION = Log4j implementation in Perl
AUTHOR = Dave Rolsky
URL = http://search.cpan.org/~drolsky/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Build.PL
BUILD_SCRIPTS = $(WORKSRC)/Build
INSTALL_SCRIPTS = $(WORKSRC)/Build
TEST_SCRIPTS = $(WORKSRC)/Build

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk
