GARNAME = POE-Test-Loops
GARVERSION = 1.354
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
#http://search.cpan.org/CPAN/authors/id/R/RC/RCAPUTO/POE-Test-Loops-1.035.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RC/RCAPUTO/ http://backpan.perl.org/authors/id/R/RC/RCAPUTO/

LIBDEPS  = apps/perl/perl

DESCRIPTION = Portable multitasking and networking framework for Perl 
AUTHOR = Rocco Caputo 
URL = http://search.cpan.org/~rcaputo/
LICENSE = Perl and GPL

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =

CONFIGURE_ARGS = --default 

include ../category.mk

