GARNAME = Convert-ASN1
GARVERSION = 0.26
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/G/GB/GBARR/

LIBDEPS = apps/perl/perl

DESCRIPTION = Standard en/decode of ASN.1 structures
AUTHOR = Graham Barr 
URL = http://cpan.uwinnipeg.ca/~gbarr
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

