GARNAME = Clone
GARVERSION = 0.31
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

#http://search.cpan.org/CPAN/authors/id/R/RD/RDF/Clone-0.31.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RD/RDF/

LIBDEPS = apps/perl/perl

DESCRIPTION = recursively copy Perl datatypes  
AUTHOR = Ray Finch
URL = http://search.cpan.org/~rdf/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

