GARNAME = Text-CSV_XS
GARVERSION = 0.90
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tgz

#http://search.cpan.org/CPAN/authors/id/H/HM/HMBRAND/Text-CSV_XS-0.73.tgz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/H/HM/HMBRAND/

LIBDEPS = apps/perl/perl

DESCRIPTION = Fast 8bit clean version of Text-CSV
AUTHOR = Jochen Wiedmann
URL = http://cpan.uwinnipeg.ca/~jwied
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

