GARNAME = Log-TraceMessages
GARVERSION = 1.4
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/E/ED/EDAVIS/ http://www.cpan.org/authors/id/E/ED/EDAVIS/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/E/ED/EDAVIS/

LIBDEPS = apps/perl/HTML-FromText

DESCRIPTION = Print developers trace messages
AUTHOR = Ed Avis
URL = http://cpan.uwinnipeg.ca/~edavis
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

