
GARNAME = List-MoreUtils
GARVERSION = 0.25_02
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/V/VP/VPARSEVAL/


LIBDEPS = apps/perl/perl

AUTHOR  = Tassilo von Parseval 
LICENSE = Perl
URL     = http://search.cpan.org/~vparseval/

DESCRIPTION =  Provide the stuff missing in List::Util  

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

