--- work/Linux-PAM-0.78/Makefile	Thu Oct 14 16:47:53 2004
+++ work/Linux-PAM-0.78/Makefile.new	Mon Feb 28 17:21:19 2005
@@ -13,7 +13,7 @@
 
 -include Make.Rules
 
-THINGSTOMAKE = libpam libpamc libpam_misc modules doc examples
+THINGSTOMAKE = libpam libpamc 
 
 all: $(THINGSTOMAKE)
 
--- work/Linux-PAM-0.78/defs/linux.defs	Wed Jun 21 00:10:46 2000
+++ work/Linux-PAM-0.78/defs/linux.defs.new	Mon Feb 28 17:36:41 2005
@@ -19,7 +19,7 @@
 LINKLIBS=-lc
 SOSWITCH=-soname
 NEEDSONAME=no
-LDCONFIG=/sbin/ldconfig
+LDCONFIG=echo
 AR=ar -cr
 RANLIB=ranlib
 FAKEROOT=
--- work/Linux-PAM-0.78/defs/redhat.defs	Wed Jun 21 00:10:46 2000
+++ work/Linux-PAM-0.78/defs/redhat.defs.new	Mon Feb 28 17:37:45 2005
@@ -22,7 +22,7 @@
 SOSWITCH=-soname
 LINKLIBS=-lc
 NEEDSONAME=no
-LDCONFIG=/sbin/ldconfig
+LDCONFIG=echo
 AR=ar -cr
 RANLIB=ranlib
 FAKEROOT=$(RPM_BUILD_ROOT)
--- work/Linux-PAM-0.78/configure.in	Wed Oct  6 16:04:34 2004
+++ work/Linux-PAM-0.78/configure.in.new	Mon Feb 28 17:42:09 2005
@@ -45,7 +45,7 @@
 USESONAME=yes			; AC_SUBST(USESONAME)
 SOSWITCH="-Wl,-soname -Wl,"	; AC_SUBST(SOSWITCH)
 NEEDSONAME=yes			; AC_SUBST(NEEDSONAME)
-LDCONFIG=/sbin/ldconfig		; AC_SUBST(LDCONFIG)
+LDCONFIG=echo			; AC_SUBST(LDCONFIG)
 
 dnl Checks for programs.
 AC_PROG_CC
@@ -263,7 +263,7 @@
 dnl Look for cracklib dictionary
 AC_MSG_CHECKING(path to cracklib dictionary)
 DICT_DIR_CANDIDATES="/usr/lib /usr/share/dict /usr/share/lib \
-  /usr/local/lib /usr/local/share/lib"
+  /usr/local/lib /usr/local/share/lib /usr/share/cracklib"
 DICT_FILE_CANDIDATES="pw_dict cracklib_dict"
 CRACKLIB_DICTPATH=""
 for d in $DICT_DIR_CANDIDATES ; do
--- work/Linux-PAM-0.78/configure.in	2005-06-22 12:53:22.000000000 +0200
+++ work/Linux-PAM-0.78/configure.in.new	2005-06-22 13:06:11.000000000 +0200
@@ -42,10 +42,25 @@
 MANMODE=644			; AC_SUBST(MANMODE)
 
 dnl These are most likely platform specific - I think HPUX differs
-USESONAME=yes			; AC_SUBST(USESONAME)
-SOSWITCH="-Wl,-soname -Wl,"	; AC_SUBST(SOSWITCH)
-NEEDSONAME=yes			; AC_SUBST(NEEDSONAME)
-LDCONFIG=echo			; AC_SUBST(LDCONFIG)
+	case $OS in
+	darwin)
+		USESONAME=no
+		SOSWITCH=
+		NEEDSONAME=no
+		LDCONFIG=echo
+		;;
+	*)
+		USESONAME=yes
+		SOSWITCH="-Wl,-soname -Wl,"
+		NEEDSONAME=yes
+		LDCONFIG=echo
+		;;
+	esac
+
+AC_SUBST(USESONAME)
+AC_SUBST(SOSWITCH)
+AC_SUBST(NEEDSONAME)
+AC_SUBST(LDCONFIG)
 
 dnl Checks for programs.
 AC_PROG_CC
@@ -318,6 +333,18 @@
 		STRIP=strip
 		CC_STATIC="-Xlinker -export-dynamic"
 		;;
+	darwin)
+		OS_CFLAGS=
+		LD_D="export MACOSX_DEPLOYMENT_TARGET=10.4; $CC -dynamiclib -undefined dynamic_lookup $LDFLAGS"
+		WARNINGS="$GCC_WARNINGS"
+		PIC="-fPIC"
+		DYNTYPE=dylib
+		LD=g++
+		LD_L="export MACOSX_DEPLOYMENT_TARGET=10.4; $CC -dynamiclib -undefined dynamic_lookup $LDFLAGS"
+		RANLIB=ranlib
+		STRIP=strip
+		CC_STATIC=
+		;;
 	sunos)
 		OS_CFLAGS="-ansi -pedantic"
 		LD_D="gcc -shared -Xlinker -x"
