GARNAME = Getopt-Declare
GARVERSION = 1.13
CATEGORIES = apps-perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/F/FA/FANGLY/

LIBDEPS = apps/perl/perl

DESCRIPTION = Declaratively Expressed Command-Line Arguments via Regular Expressions
AUTHOR = Damian Conway
URL = http://search.cpan.org/~dconway/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

