GARNAME = Task-Weaken
GARVERSION = 1.03
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/

LIBDEPS = apps/perl/Error apps/perl/Digest-SHA1

DESCRIPTION = Ensure that a platform has weaken support  
LICENSE = Perl
URL = http://search.cpan.org/~adamk/
AUTHOR = Adam Kennedy 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

