GARNAME = Sub-Uplevel
GARVERSION = 0.22
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/D/DA/DAGOLDEN/ http://backpan.perl.org/authors/id/D/DA/DAGOLDEN/

LIBDEPS = apps/perl/perl

DESCRIPTION = apparently run a function in a higher stack frame  
AUTHOR = David Golden
URL = http://search.cpan.org/~DAGOLDEN/Sub-Uplevel/
LICENSE = OpenSSL

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

