GARNAME = m4
GARVERSION = 1.4.16
CATEGORIES = tools-devel
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

BININSTALL_IGNORE = true

#http://ftp.gnu.org/gnu/m4/m4-1.4.13.tar.gz
MASTER_SITES = http://ftp.gnu.org/gnu/m4/

LIBDEPS =

DESCRIPTION = GNU M4
AUTHOR = GNU
URL = http://www.gnu.org/software/m4/
LICENSE = GNU GPL

CONFIGURE_SCRIPTS = $(WORKSRC)/configure
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS = --prefix=$(PREFIX)
BUILD_ARGS =  

include ../category.mk

