GARNAME = DateTime-Locale
GARVERSION = 0.45
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/

LIBDEPS = apps/perl/Params-Validate apps/perl/List-MoreUtils

DESCRIPTION = Localization support for DateTime.pm
AUTHOR = Dave Rolsky 
URL = http://cpan.uwinnipeg.ca/~drolsky
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Build.PL
BUILD_SCRIPTS = $(WORKSRC)/Build
INSTALL_SCRIPTS = $(WORKSRC)/Build
TEST_SCRIPTS = $(WORKSRC)/Build

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

