GARNAME = PlRPC
GARVERSION = 0.2020
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
DISTNAME = $(GARNAME)

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/MN/MNOONING/PlRPC/

LIBDEPS = apps/perl/Net-Daemon

DESCRIPTION = Perl Remote Method Invocation
AUTHOR = Jochen Wiedmann 
URL = http://cpan.uwinnipeg.ca/~jwied
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

