GARNAME = Test-Tester
GARVERSION = 0.107
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz
PATCHFILES = 

#http://search.cpan.org/CPAN/authors/id/F/FD/FDALY/Test-Tester-0.107.tar.gz
MASTER_SITES = http://search.cpan.org/CPAN/authors/id/F/FD/FDALY/

LIBDEPS = apps/perl/perl

DESCRIPTION = Ease testing test modules built with Test::Builder  
AUTHOR = Fergal Daly
URL = http://search.cpan.org/~fdaly/
LICENSE = Perl

AUTOTEST = 

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS =  $(WORKSRC)/Makefile

BUILD_ARGS =  

include ../category.mk

