GARNAME = Getargs-Long
GARVERSION = 1.1003
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://www.cpan.org/authors/id/D/DC/DCOPPIT/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/D/DC/DCOPPIT/ http://search.cpan.org/CPAN/authors/id/D/DC/DCOPPIT/

LIBDEPS = apps/perl/Log-Agent

DESCRIPTION = Named subroutine arguments, with optional type checking
AUTHOR = David Coppit
URL = http://search.cpan.org/~dcoppit/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

