GARNAME = Crypt-CBC
GARVERSION = 2.30
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/L/LD/LDS/

LIBDEPS = apps/perl/perl 

DESCRIPTION = Cipherblock chaining for Crypt-DES/IDEA
AUTHOR =   Lincoln D. Stein 
URL = http://cpan.uwinnipeg.ca/~lds
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

