GARNAME = Try-Tiny
GARVERSION = 0.20
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/D/DO/DOY/

LIBDEPS = apps/perl/perl

DESCRIPTION = minimal try/catch with proper localization of $@ 
URL = http://search.cpan.org/~doy/Try-Tiny-0.09/
AUTHOR = Jesse Luehrs
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

