GARNAME = IO-Pipely
GARVERSION = 0.002
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz


MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RC/RCAPUTO/ http://backpan.perl.org/authors/id/R/RC/RCAPUTO/

LIBDEPS = apps/perl/Exporter-Lite

AUTHOR = RCAPUTO
URL = http://backpan.perl.org/authors/id/R/RC/RCAPUTO/
LICENSE = Perl

DESCRIPTION = pipes tools

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

