GARNAME = Email-Date-Format
GARVERSION = 1.002
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/ http://backpan.perl.org/authors/id/R/RJ/RJBS/

LIBDEPS = apps/perl/perl

DESCRIPTION = produce RFC 2822 date strings 
AUTHOR = Ricardo Signes
URL = http://search.cpan.org/~rjbs/
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

