GARNAME = MIME-Types
GARVERSION = 1.31
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/MA/MARKOV/

LIBDEPS = apps/perl/Test-Pod

DESCRIPTION = Definition of one MIME type
AUTHOR = Mark Overmeer
URL = http://cpan.uwinnipeg.ca/~markov
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

