GARNAME = Log-Agent
GARVERSION = 0.307
CATEGORIES = apps-tools
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://www.cpan.org/authors/id/M/MR/MROGASKI/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/M/MR/MROGASKI/ http://search.cpan.org/CPAN/authors/id/M/MR/MROGASKI/

LIBDEPS = apps/perl/perl

DESCRIPTION = Logging Agent
AUTHOR = Mark Rogaski
URL = http://search.cpan.org/~mrogaski
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

