GARNAME = Class-Load
GARVERSION = 0.06
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/S/SA/SARTAK/

LIBDEPS = apps/perl/Test-Fatal

DESCRIPTION = a working (require "Class::Name") and more 
URL = http://search.cpan.org/dist/Class-Load/
AUTHOR = Shawn M Moore 
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

