GARNAME = SOAP-Transport-TCP
GARVERSION = 0.715
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/MK/MKUTTER/

LIBDEPS = apps/perl/SOAP-Lite

DESCRIPTION = SOAP toolkit for perl
AUTHOR = Byrne Reese
URL = http://cpan.uwinnipeg.ca/~byrne
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =

include ../category.mk

