GARNAME = Params-Util
GARVERSION = 1.01
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/


LIBDEPS = apps/perl/perl
AUTHOR  = Adam Kennedy
LICENSE = Perl
URL     = http://search.cpan.org/~adamk

DESCRIPTION =  Simple, compact and correct param-checking functions  

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

