GARNAME = Exporter-Lite
GARVERSION = 0.02
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = $(CPAN_MIRROR)/authors/id/M/MS/MSCHWERN/ http://www.cpan.org/authors/id/M/MS/MSCHWERN/ ftp://sunsite.cnlab-switch.ch/mirror/CPAN/authors/id/M/MS/MSCHWERN/

LIBDEPS = apps/perl/perl

DESCRIPTION = Lightweight exporting of variables
AUTHOR = Michael G Schwern 
URL  = http://cpan.uwinnipeg.ca/~mschwern 
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

