GARNAME = Error
GARVERSION = 0.17019
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/S/SH/SHLOMIF/ http://backpan.perl.org/authors/id/S/SH/SHLOMIF/

LIBDEPS = apps/perl/perl

DESCRIPTION = Error/exception handling in an OO-ish way
AUTHOR = Arun Kumar U
URL = http://cpan.uwinnipeg.ca/~uarun
LICENSE = Perl

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

include ../category.mk

