GARNAME = Class-Singleton
GARVERSION = 1.4
CATEGORIES = perl
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/A/AB/ABW/

LIBDEPS = apps/perl/perl

DESCRIPTION = Implementation of a "Singleton" class
AUTHOR = Andy Wardley
URL = http://cpan.uwinnipeg.ca/~abw
LICENSE = Artistic

CONFIGURE_SCRIPTS = $(WORKSRC)/Makefile.PL
BUILD_SCRIPTS = $(WORKSRC)/Makefile
INSTALL_SCRIPTS = $(WORKSRC)/Makefile
TEST_SCRIPTS = $(WORKSRC)/Makefile

CONFIGURE_ARGS =  
BUILD_ARGS =  

include ../category.mk

